name: "Github Action for Helm on EKS (with aws-iam-authenticator)"
description: "Authenticates on EKS clusters using aws-iam-authenticator and executes Helm commands. Can also be used with kubectl commands."
branding:
  icon: 'anchor'  
  color: 'blue'
inputs:
  app_name:
    description: "Application Name" 
    required: true
  command:
    description: "Your command (kubectl or helm)" 
    required: true
  namespace: 
    description: "The k8s namespace to use"
    required: true 
  hostname:
    description: "Hostname"
    required: false
  imageTag: 
    description: "Image Tag"
    required: false 
  graffitiSecret:
    description: "graffitiSecret"
    required: false
  accountId:
    description: "accountId"
    required: false
outputs:
  result:
    description: "Output returned by your Helm or kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
